"""Initial migration - Sistema Abertura Contas

Revision ID: 02e74ab3b348
Revises: 
Create Date: 2025-10-09 11:07:22.692623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02e74ab3b348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencia', schema=None) as batch_op:
        batch_op.alter_column('dv_agencia',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
        batch_op.alter_column('uf',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)

    with op.batch_alter_table('conta_convenio', schema=None) as batch_op:
        batch_op.alter_column('dv_conta',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)

    with op.batch_alter_table('remessa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situacao_enum', sa.Enum('EM_PREPARACAO', 'ENVIADO', 'AGUARDANDO_RETORNO', 'APROVADO', 'CONTA_ABERTA', 'ERRO', name='situacaoenum'), nullable=False))
        batch_op.drop_column('situacao')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('perfil_enum',
               existing_type=postgresql.ENUM('Administrador', 'Operador', 'Monitor', name='perfil_enum'),
               type_=sa.Enum('ADMIN', 'OPERADOR', 'MONITOR', name='perfilenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Monitor'::perfil_enum"))
        batch_op.alter_column('status_enum',
               existing_type=postgresql.ENUM('Ativo', 'Inativo', name='status_enum'),
               type_=sa.Enum('ATIVO', 'INATIVO', name='statusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Ativo'::status_enum"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('status_enum',
               existing_type=sa.Enum('ATIVO', 'INATIVO', name='statusenum'),
               type_=postgresql.ENUM('Ativo', 'Inativo', name='status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Ativo'::status_enum"))
        batch_op.alter_column('perfil_enum',
               existing_type=sa.Enum('ADMIN', 'OPERADOR', 'MONITOR', name='perfilenum'),
               type_=postgresql.ENUM('Administrador', 'Operador', 'Monitor', name='perfil_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Monitor'::perfil_enum"))

    with op.batch_alter_table('remessa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situacao', postgresql.ENUM('Em Preparação', 'Enviado', 'Aguardando retorno', 'Pendente de envio', 'Conta Aberta', 'Erro', name='situacao_enum'), server_default=sa.text("'Em Preparação'::situacao_enum"), autoincrement=False, nullable=False))
        batch_op.drop_column('situacao_enum')

    with op.batch_alter_table('conta_convenio', schema=None) as batch_op:
        batch_op.alter_column('dv_conta',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)

    with op.batch_alter_table('agencia', schema=None) as batch_op:
        batch_op.alter_column('uf',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('dv_agencia',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###
